language: csharp
solution: KiotlogDBF.sln
mono: none
dotnet: 5.0
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - KL_PGDATABASE="kl_tests"
  - KL_PGUSER="kiotlog"
  - KL_PGPASS="kiotlog"
  - KL_PGPORT=5432
  - KL_PGHOST=localhost

before_script:
  - set -ef && cd / && sudo -u postgres -- psql -p $KL_PGPORT -c "CREATE ROLE $KL_PGUSER PASSWORD 'md5b23e166616b9c6ce6684731cffc468b8' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" && cd -

script:
  - dotnet build
  - dotnet tool install -g dotnet-ef
  - set -ef && cd Migrations && dotnet ef dbcontext info && dotnet ef migrations list && dotnet ef database update && cd ..
  - set -ef && cd KiotlogDBF.Tests && dotnet test && cd ..
