language: csharp
solution: KiotlogDBF.sln
mono: none
dotnet: 2.1.105
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - KL_PGDATABASE="kl_tests"
  - KL_PGUSER="kiotlog"
  - KL_PGPASS="kiotlog"
  - KL_PGPORT=5433
  - KL_PGHOST=localhost

before_script:
  - cd /; sudo -u postgres -- psql -c "CREATE ROLE $KL_PGUSER PASSWORD 'md5b23e166616b9c6ce6684731cffc468b8' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;"; cd -

script:
  - dotnet build
  - cd Migrations; dotnet ef dbcontext info; dotnet ef migrations list; dotnet ef database update; cd ..
  - cd KiotlogDBF.Tests; dotnet xunit -verbose; cd ..